# Generated by Django 4.2.2 on 2023-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="location")),
                ("items", models.CharField(max_length=10000, verbose_name="items")),
            ],
        ),
    ]
